spring.application.name=demo
# application.properties
spring.ai.openai.api-key=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
spring.data.mongodb.uri=mongodb+srv://kws06009:hanshin2025@hybridchat.nmexese.mongodb.net/HybridChat?retryWrites=true&w=majority&appName=HybridChat


