spring.application.name=demo
# application.properties
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.data.mongodb.uri=mongodb+srv://kws06009:hanshin2025@hybridchat.nmexese.mongodb.net/ChatDB?retryWrites=true&w=majority&appName=HybridChat
openai.model=gpt-4o

# Dialogflow Configuration
dialogflow.project-id=hybrid-chatbot
spring.cloud.gcp.credentials.location=classpath:credentials/dialogflow-service-account.json